### ISSUE TITLE
Nice work! This repo only contains the dataset, instead of the annotation tools?

### ISSUE THREAD

**Issue by StarCycle** [yunongLiu1/IKEA-Manuals-at-Work#2]
Hello @yunongLiu1,

Thank you for sharing this nice dataset! Just to check, this repo only contains the dataset and the dataloader, without your annotation pipeline. Is my understanding correct?

Have a nice day~

**Comment by yunongLiu1** [comment]
Hello @StarCycle,

Thank you for your kind words and for your interest in our dataset! 😊

Yes, you are correct — this repository currently includes only the dataset and the dataloader. However, we do plan to release the annotation tool in the near future, so please stay tuned for updates!

Happy Holidays!
