### ISSUE TITLE
Confirmation of current dataset and dataset expansion.

### ISSUE THREAD

**Issue by Owensun0402** [yunongLiu1/IKEA-Manuals-at-Work#3]
Hi @yunongLiu1,

Thanks for the amazing work! I noticed that while the dataset contains 36 furniture models, there seem to be additional furniture models in the `/data/manual_masks/`, `/data/parts/`, and `/data/pdfs/` directories compared to `/data/manual_img/` and `data.json`. Are there any plans to expand the dataset to include all the furniture models found in those directories?

Happy holidays!

**Comment by yunongLiu1** [comment]
Hi @Owensun0402 ,

Thank you for your kind words and for taking a close look at our dataset! 😊

Regarding your observation, the additional furniture models in the directories are from the original IKEA manual dataset. At this time, we don’t have plans to expand the dataset to include all those furniture models.

Wishing you happy holidays as well! 🎄✨
